name: Docs Only Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build_docfx_docu_ghPage:
    runs-on: ubuntu-latest
    name: A job to build docu for GitHub-Page
    steps:
    - uses: actions/checkout@v1
    # ...
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json

    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docs # docfx's default output directory is _site 
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
